# 2.15 高级类型

本章节会介绍NLang中内置的高级类型。这些类型用于实现某个目的，并且为特定功能提供了底层封装。

## Iterable

`Iterable`类型用于表示可迭代对象。可迭代对象包括：[数组](./6.%20数组.md)、[元组](./8.%20元组.md)

对象并非可迭代对象，但通过对象方法（例如`keys`、`values`、`entries`）可以对其进行迭代。

要迭代一个特定可迭代对象，可以使用[控制流 - 迭代](./11.%20控制流.md#迭代)

## Promise

`Promise`类型是NLang中对于异步任务的高级封装。`Promise`可以用于表示正在进行的异步任务的状态，包括：
- 任务成功（`fulfilled`）
- 任务失败（`rejected`）
- 任务进行中（`pending`）
- 任务已中断（`canceled`）

任何非进行（`pending`）状态的`Promise`都会被视为已完成（`settled`）。

`Promise`类型在被中断的时候，会同步触发中断处理器和`finally`监听器。

### then

`then`方法用于在Promise上添加一个任务成功（`fulfilled`）监听器。

调用该方法会返回新的`Promise`，其解析值为上一个`then`回调函数的返回值。

- 参数
  - `onFulfilled(value) => any`：任务成功（`fulfilled`）处理器，`value`为上一个`Promise.then`的解析值
- 返回值
  - `Promise`：新的`Promise`

- 示例
  ```javascript
  set promise Promise.resolve("success")

  promise.then(result => {
    console.log(result) // "success"
  })
  ```

链式调用的例子：  
```javascript
set promise Promise.resolve(1).then(res => res * 2).then(res => res * 3)

promise.then(res => {
  console.log(res) // 6
})
```

### catch

`catch`方法会在Promise失败（`rejected`）时被调用。

调用该方法会返回原`Promise`。

- 参数
  - `onRejected(error) => any`：任务失败（`rejected`）处理器，`error`为上一个`Promise.catch`的解析值
- 返回值
  - `this`

### finally

`finally`方法会在`Promise`进入已完成（`fulfilled`、`rejected`）或已中断（`canceled`）状态后被调用，用于注册一个无论结果如何都会执行的回调。

- 参数
  - `onFinally() => void`：结尾处理器，不接收任何参数
- 返回值
  - `this`

- 示例
  ```javascript
  set promise Promise.resolve(42)

  promise
    .then(v => v + 1)
    .catch(err => console.error(err))
    .finally(() => {
      console.log("clean up")
    })
  ```

### onCancel

`onCancel`方法用于在`Promise`被中断（`canceled`）时注册回调。该回调在中断发生时会同步触发，并且 **不会** 接收任何参数。

- 参数
  - `handler() => void`：中断处理器
- 返回值
  - `this`

- 示例
  ```javascript
  function! createTask() {
    var task null
    var promise Promise(resolve => {
        set task fetch(/* ... */).then(resolve)
    })

    promise.onCancel(() => {
        task.cancel()
    })
  }

  function! main() {
    var task createTask()

    task.then(res => {
        console.log(res)
    })

    setTimeout(() => {
        task.cancel()

        console.log("task timeout")
    }, 1000)
  }
  ```

## 下一步
